### ISSUE TITLE
Duplicated runtime in deployed dir

### ISSUE THREAD

**Issue by RealThanhpv** [dlemmermann/JPackageScriptFX#11]
I hope I was wrong 
I would increase the package size
![image](https://user-images.githubusercontent.com/94328752/143228548-ce55f0cc-6dbd-4984-ba35-a3e1aa427f22.png)

And this is from Oracle site 
https://docs.oracle.com/en/java/javase/17/jpackage/packaging-overview.html#GUID-C0AAEB7D-1FAB-4E20-B52C-E2401AC2BABE
![image](https://user-images.githubusercontent.com/94328752/143228654-b8ae79c8-96eb-4be3-9d44-07b1e3b267a3.png)

**Comment by dlemmermann** [comment]
Not sure what you are trying to tell us? Are you surprised to see that many DLL files?

**Comment by RealThanhpv** [comment]
@dlemmermann it seems duplicated with the runtime folder

**Comment by dlemmermann** [comment]
Are the DLL files also all showing up in the runtime folder?

**Comment by dlemmermann** [comment]
@mipastgt I don't think this is something the scripts are doing, right? This is jpackage's doing?

**Comment by RealThanhpv** [comment]
@dlemmermann I think so
![image](https://user-images.githubusercontent.com/94328752/143229698-540f5d75-5586-4096-b3b0-691d164c986c.png)

**Comment by dlemmermann** [comment]
This is a jpackage issue https://bugs.openjdk.java.net/browse/JDK-8230863

Should be fixed for versions > 14.

**Comment by RealThanhpv** [comment]
@dlemmermann Thanks

**Comment by mipastgt** [comment]
Yes, I remember this old issue. Should be fixed now in newer versions.
