### ISSUE TITLE
Failed to launch JVM with fxml

### ISSUE THREAD

**Issue by RealThanhpv** [dlemmermann/JPackageScriptFX#12]
I have tried with a very simple node (AnchorPane) with Fxml. It packaged successfully but failed to launch.

**Comment by dlemmermann** [comment]
This is not a proper bug report / issue / ticket. Without any additional information there is nothing anyone can do for you.

**Comment by dlemmermann** [comment]
Run the app from the **command line** and see if there is any output.

**Comment by RealThanhpv** [comment]
@dlemmermann I am sorry. This is all I got
And the code is very simple that the root node is an AnchorPane extend

![image](https://user-images.githubusercontent.com/94328752/143241420-decf6d4e-0cb0-479a-9520-1ba04a7f21da.png)

**Comment by dlemmermann** [comment]
Run from the command line please.

**Comment by RealThanhpv** [comment]
Yeah I did 
![image](https://user-images.githubusercontent.com/94328752/143242156-ddfefd52-8e75-4971-8b2e-ada48a531cb9.png)

**Comment by dlemmermann** [comment]
Then I do not know, sorry.

**Comment by RealThanhpv** [comment]
Then I got the same problem when trying to jpackage without the script and found that it is because of errant resource path.
Setting the resource path according to the package names works for me.

**Comment by Lakinator** [comment]
@RealThanhpv I am currently having the same problem, could you please explain how exactly you solved this problem? Which resource path do you mean?
