### ISSUE TITLE
can't run test app in mac

### ISSUE THREAD

**Issue by yishenggudou** [dlemmermann/JPackageScriptFX#13]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/380657/157795308-449addb7-3b0e-4237-961c-a75d2dca41b5.png">

<img width="586" alt="image" src="https://user-images.githubusercontent.com/380657/157795289-05b4601a-6b32-44d2-a7ee-1b5e73b2153e.png">

**Comment by HanSolo** [comment]
I’m not speaking chinese but it looks like you double clicked the pkg installer and it says that the author is not registered or something similar. If you open the finder and right click on the pkg file and select open, it should give you the option of open the app. Did you try that? Looks like the reason for this is that the pkg file is not notarized.

**Comment by mipastgt** [comment]
Closing this because there was no feedback from the author and the comment made by @HanSolo indicates indeed the most likely cause for the problem.
