### ISSUE TITLE
Resource Folder not being copied to final package.

### ISSUE THREAD

**Issue by FabianHummel** [dlemmermann/JPackageScriptFX#16]
Hello, I have a javafx project, and when using this script to package the program my resources are not being copied over to the app image. The project is also hosted on github at https://github.com/FabianHummel/Kotlin-Tetrux-Game. My folder structure looks like the following:

```
root
  - res (marked as resources root)
  - src (marked as source root)
  - build-app-mac.sh
  - pom.xml
```

When exporting to an app-image, there is no resource folder whatsoever and the application crashes. Am I doing something wrong here?

**Comment by mipastgt** [comment]
Sorry, but you are not following the standard conventions for the Maven project structure. So, you are on your own to debug that.

**Comment by FabianHummel** [comment]
I fixed it by generating a new maven project and leaving the structure as is. Thank you!

**Comment by mipastgt** [comment]
Closed because the issue could be fixed by using the default project structure.
