### ISSUE TITLE
How to use with fxml? 

### ISSUE THREAD

**Issue by TM00** [dlemmermann/JPackageScriptFX#17]
Hi, thanks for creating this tool. I'm struggling to get it to work using fxml files. I amended module 2 as follows as an example:

```
public class ModuleLabel2 extends Pane {

    public ModuleLabel2() {
        //super("Module Label 2");

        FXMLLoader fxmlLoader = new FXMLLoader(ModuleLabel2.class.getResource("module2Test.fxml"));
        try {
            VBox box  =fxmlLoader.load();
            this.getChildren().add(box);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        
    }
}
```
With the fxml file:

```
<?xml version="1.0" encoding="UTF-8"?>

<?import javafx.geometry.Insets?>
<?import javafx.scene.control.Label?>
<?import javafx.scene.layout.VBox?>

<?import javafx.scene.control.Button?>
<VBox alignment="CENTER" spacing="20.0" xmlns:fx="http://javafx.com/fxml"
      fx:controller="com.dlsc.jpackage.module2.Module2Controller">
    <padding>
        <Insets bottom="20.0" left="20.0" right="20.0" top="20.0"/>
    </padding>
    <Label fx:id="welcomeText" text="Label"/
</VBox>

```
And a controller:

```
package com.dlsc.jpackage.module2;

import javafx.fxml.FXML;
import javafx.scene.control.Label;

public class Module2Controller {
    @FXML
    private Label welcomeText;
}
```

This is the location of the files relative to each other:
![file tree](https://user-images.githubusercontent.com/23653718/211139626-aef21b67-206d-42e5-ba00-e21d867f5a9d.png)

When I run the _install_ command it builds fine, when I run the exe (in target\installer\JPackageScriptFX\JPackageScriptFX.exe) I get this error:

![image](https://user-images.githubusercontent.com/23653718/211139772-69a2fd64-0941-4549-9383-065089ef930f.png)

I left the App.java file unchanged. If I remove Module 2 from the App method (as shown below) and _install_ again, the exe runs fine:

```
        Label defaultLocaleLabel = new Label(Locale.getDefault().getDisplayLanguage());
        ModuleLabel1 label1 = new ModuleLabel1();
       // ModuleLabel2 label2 = new ModuleLabel2();
        VBox box = new VBox(20, defaultLocaleLabel, label1/*,label2*/);
        box.setAlignment(Pos.CENTER);
        box.setPadding(new Insets(20));
        Scene scene = new Scene(box);

```

![image](https://user-images.githubusercontent.com/23653718/211139954-29a90d41-2f13-4edd-86a8-7463d79b8d1e.png)

Hence I think the issue relates to how the fxml files are referenced. I did see a similar issue logged, but the solution wasn't clear. Therefore I opened a new one.  

Side question - how do I run the jar which is produced by the _install_ command (to check the stacktrace)? I tried the following two commands which doesn't seem to work. Note this was tested on the non-fxml version so it should work.

![cmd line](https://user-images.githubusercontent.com/23653718/211140109-61de55d5-cd7f-4c6b-9e08-7a688b51b357.png)

Thanks a lot for the help. It is greatly appreciated.

**Comment by mipastgt** [comment]
You can run the app as a regualar Java application like this in order to see what is going wrong.
From the folder jpackagefx-main call
```
$JAVA_HOME/bin/java -cp "target/installer/input/libs/*" com.dlsc.jpackagefx.AppLauncher
```
You may have to adapt that to the Windows calling conventions. Ignore the warning
`Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6f1eab88'`

**Comment by mipastgt** [comment]
In your case this looks like a resource loading problem. Try putting a `/` in front of the file name like this.
`FXMLLoader fxmlLoader = new FXMLLoader(ModuleLabel2.class.getResource("/module2Test.fxml"));`
I haven't tried it, so this is just a guess.

**Comment by TM00** [comment]
Thank you! I managed to run the app from the command line and adding the `/` fixed the fxml problem. 

I was a "location is not set" error causing the issue.
![cmd line](https://user-images.githubusercontent.com/23653718/211182040-33a31fdb-ad49-41c4-b87c-7cc86b093af5.png)
