### ISSUE TITLE
Could you provide package results! thanks 

### ISSUE THREAD

**Issue by 0oc** [dlemmermann/JPackageScriptFX#2]

**Comment by dlemmermann** [comment]
What do you mean? What results?

**Comment by 0oc** [comment]
DMG  or EXE ?

**Comment by dlemmermann** [comment]
Just run the build and you will have the results. Why do you think it would make sense to include the results? That would be like projects checking in their .class files :-)

**Comment by 0oc** [comment]
Sorry  i am noob.  just want try  run it .

**Comment by dlemmermann** [comment]
Yes, follow the instructions provided in the README. If you then run into an issue because something does not build, then please submit another ticket.
