### ISSUE TITLE
Any plan to support Linux based OS?

### ISSUE THREAD

**Issue by UltraBurstXD** [dlemmermann/JPackageScriptFX#7]
These instructions found here only favors Windows and Mac users. What about us Linux fanatic users?

**Comment by mipastgt** [comment]
Conceptually, with just a few minor changes, the Mac version should also work for Linux but I simply did not have the time yet to give it a try. You might volunteer and provide me with some feedback.

**Comment by mipastgt** [comment]
You are really lucky. I just realized that I will need a Linux package for a project of mine within the next few days anyway, so I just sat down and updated the tutorial code. (Documentation update is still pending.) I tested creating, installing and uninstalling of a Debian package on Ubuntu 20.04. RPM is still untested. Maybe you can provide some feedback how it worked for you.

**Comment by UltraBurstXD** [comment]
OK. I will.
